#
# APM Copter-4.5.5 SITL testing environment for MAVSDK based on Ubuntu 22.04.
# Author: Yogesh Khedar <yogeshkhedar@gmail.com>
#
FROM --platform=linux/amd64 khedar/mavsdk-ubuntu-22.04
MAINTAINER Yogesh Khedar <yogeshkhedar@gmail.com>

ENV FIRMWARE_DIR ${WORKDIR}../ArduPilot

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get --quiet -y --no-install-recommends install locales  \
                                python3 python3-wheel gnupg gcc lcov rsync screen shellcheck psmisc \
                                && apt-get -y autoremove \
                                && apt-get clean autoclean \
                                && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV COPTER_VERSION Copter-4.5.5

RUN git clone https://github.com/ArduPilot/ardupilot.git ${FIRMWARE_DIR}
RUN git -C ${FIRMWARE_DIR} checkout ${COPTER_VERSION}
RUN git -C ${FIRMWARE_DIR} submodule update --init --recursive

RUN cd ${FIRMWARE_DIR} && sed -i 's/sudo //' Tools/environment_install/install-prereqs-ubuntu.sh && \
    sed -i '6,9d' Tools/environment_install/install-prereqs-ubuntu.sh && \
    sed -i '/usermod -a -G dialout/d' Tools/environment_install/install-prereqs-ubuntu.sh && \
    sed -i 's/--user//' Tools/environment_install/install-prereqs-ubuntu.sh && \
    sed -i 's/pip setuptools/pip setuptools~=70.0/' Tools/environment_install/install-prereqs-ubuntu.sh && \
    sed -i 's/==3.3.4//' Tools/environment_install/install-prereqs-ubuntu.sh



RUN cd ${FIRMWARE_DIR} && bash Tools/environment_install/install-prereqs-ubuntu.sh -y

ENV APM_VEHICLE ArduCopter
ENV APM_FRAME quad

# need to install empy 3.3.4 specifically now else dronecangen fails.
RUN pip3 install empy==3.3.4
RUN cd ${FIRMWARE_DIR} && ./waf distclean && ./waf configure --board sitl && ./waf copter


